#!/usr/bin/env python

import sys
import json


def main(args):
    data = json.load(sys.stdin)
    for row in format_rows(data):
        print row

    return True


def format_rows(data, separator=" | "):
    cols = data["head"]["vars"]
    yield separator.join(cols)
    for row in data["results"]["bindings"]:
        yield separator.join(row[col]["value"] for col in cols)


if __name__ == "__main__":
    status = not main(sys.argv)
    sys.exit(status)
