#!/usr/bin/env bash

usage() {
cat << EOS
Sesame CLI

command-line interface for OpenRDF Sesame triplestores

Usage:
  $ sesame-cli [options] <host> <command> [arguments]

Options:
  -h
    display this help message
  -i
    include inferences
  -f
    output format
    see http://www.openrdf.org/doc/sesame2/system/ch08.html#table-rdf-formats or
    http://www.openrdf.org/doc/sesame2/system/ch08.html#table-var-binding-formats
  -r <repository>
    select repository

Commands:
  list <repos|graphs|triples>
    display all repositories, contexts or triples
  query [query]
    perform SPARQL query (optionally read from STDIN)
  add [triples]
    insert triples (as N-Triples; optionally read from STDIN)
  clear [name]
    remove all triples within the given repository or graph
    if name is provided, the respective graph will be cleared - otherwise the
    current repository will be cleared
EOS
}

if [ -z "$*" ]; then
	usage
	exit 1
fi

while getopts "f:hir:" option; do
	case $option in
		f)
			format="$OPTARG"
			;;
		h)
			usage
			exit 1
			;;
		i)
			include_inferences=true
			;;
		r)
			repo="$OPTARG"
			;;
	esac
done
shift $(($OPTIND - 1)) # drop option arguments

host=${1:?}
shift
cmd=${1:?}
cmd="cmd_$cmd" # avoids reserved names / external commands
shift
args=$@

# commands

cmd_list() {
	case "$@" in
		repos)
			list_repos
			;;
		graphs)
			list_graphs
			;;
		triples)
			list_triples
			;;
		*)
			echo "invalid argument: $@"
			exit 1
			;;
	esac
}

cmd_query() {
	query="$@"
	if [ -z "$query" ]; then
		query=`cat -`
	fi
	pysrc="import sys; import urllib; print urllib.quote(sys.stdin.read());"
	query=`echo "$query" | python -c "$pysrc"`

	if [ -z "$format" ]; then
		format="application/sparql-results+json"
	fi

	curl -s -H "Accept: $format" "$host/repositories/$repo?query=$query"
}

cmd_add() {
	# TODO
	echo "error: not yet implemented"
	exit 1
}

cmd_clear() {
	# TODO
	echo "error: not yet implemented"
	exit 1
}

# util

ensure_repo() {
	if [ -z "$repo" ]; then
		echo "error: repository not specified"
		exit 1
	fi
}

list_repos() {
	pysrc='print "\n".join("%s: %s" % (item["id"]["value"], item["title"]["value"]) for item in data["results"]["bindings"])'
	pysrc="import sys; import json; data = json.load(sys.stdin); $pysrc"
	curl -s -H "Accept: application/sparql-results+json" "$host/repositories" | \
		python -c "$pysrc"
}

list_graphs() {
	ensure_repo
	pysrc='print "\n".join(item["contextID"]["value"] for item in data["results"]["bindings"])'
	pysrc="import sys; import json; data = json.load(sys.stdin); $pysrc"
	curl -s -H "Accept: application/sparql-results+json" \
			"$host/repositories/$repo/contexts" | \
		python -c "$pysrc"
}

list_triples() {
	ensure_repo
	if [ -z "$format" ]; then
		format="application/x-turtle"
	fi
	curl -s -H "Accept: $format" "$host/repositories/$repo/statements"
}

# dispatch

$cmd "$args"
