#!/usr/bin/env bash

usage() {
cat << EOS
Sesame CLI

command-line interface for OpenRDF Sesame triplestore

Usage:
  $ sesame-cli [options] <host> <repository> <command> [arguments]

Options:
  -h
    display this help message
  -i
    include inferences

Commands:
  list <repos|graphs|triples>
    display all repositories, contexts or triples
  query [query]
    perform SPARQL query (optionally read from STDIN)
  add [triples]
    insert triples (as N-Triples; optionally read from STDIN)
  clear [name]
    remove all triples within the given repository or graph
    if name is provided, the respective graph will be cleared - otherwise the
    current repository will be cleared
EOS
}

while getopts "hi" option; do
    case $option in
        h)
            usage
            exit 1
            ;;
        i)
            include_inferences=true
            ;;
    esac
done
shift $(($OPTIND - 1)) # drop option arguments

host=${1:?}
shift
repo=${1:?}
shift
cmd=${1:?}
cmd="cmd_$cmd" # avoids reserved names / external commands
shift
args=$@

# commands

cmd_list() {
	echo "listing: $@"
}

cmd_query() {
	echo "querying: $@"
}

cmd_add() {
	echo "adding: $@"
}

cmd_clear() {
	echo "clearing: $@"
}

# dispatch

$cmd $args
